before_install:
    - sudo apt-get install perl git
    - sudo apt-get install libjson-perl
    - sudo apt-get install openssh-server
    - ssh-keyscan -t rsa localhost | sudo tee /etc/ssh/ssh_known_hosts

before_script:
    - git fetch --unshallow
    - sudo adduser --shell /bin/sh --disabled-password --gecos Frodo frodo
    - sudo adduser --shell /bin/sh --disabled-password --gecos Sam sam
    - sudo adduser --shell /bin/sh --disabled-password --gecos Gollum gollum
    - mkdir -p /tmp/keys
    - ssh-keygen -t rsa -f /tmp/keys/admin -N "" -q
    - ssh-keygen -t rsa -f /tmp/keys/server-frodo -N "" -q
    - ssh-keygen -t rsa -f /tmp/keys/server-sam -N "" -q
    - ssh-keygen -t rsa -f /tmp/keys/server-gollum -N "" -q
    - cat /tmp/keys/admin.pub >> /tmp/keys/authorized_keys
    - cat /tmp/keys/server-frodo.pub >> /tmp/keys/authorized_keys
    - cat /tmp/keys/server-sam.pub >> /tmp/keys/authorized_keys
    - cat /tmp/keys/server-gollum.pub >> /tmp/keys/authorized_keys
    - chmod -R go+rX /tmp/keys
    - sudo -u frodo -i mkdir .ssh
    - sudo -u frodo -i cp /tmp/keys/server-frodo .ssh/id_rsa
    - sudo -u frodo -i cp /tmp/keys/authorized_keys .ssh/authorized_keys
    - sudo -u frodo -i chmod -R go-rwx .ssh
    - sudo -u sam -i mkdir .ssh
    - sudo -u sam -i cp /tmp/keys/server-sam .ssh/id_rsa
    - sudo -u sam -i cp /tmp/keys/authorized_keys .ssh/authorized_keys
    - sudo -u sam -i chmod -R go-rwx .ssh
    - sudo -u gollum -i mkdir .ssh
    - sudo -u gollum -i cp /tmp/keys/server-gollum .ssh/id_rsa
    - sudo -u gollum -i cp /tmp/keys/authorized_keys .ssh/authorized_keys
    - sudo -u gollum -i chmod -R go-rwx .ssh
    - cp /tmp/keys/admin ~/.ssh/id_rsa
    - cp /tmp/keys/admin.pub ~/.ssh/authorized_keys
    - chmod -R go-rwx ~/.ssh

script:
    - prove
    - prove t/mirror-test
