#!/usr/bin/perl

# Set alternates if option reference.repo is set
# ----------------------------------------------------------------------

use FindBin;

use lib $ENV{GL_LIBDIR};
use Gitolite::Rc;
use Gitolite::Common;
use Gitolite::Conf::Load;

use strict;
use warnings;

my $RB = $rc{GL_REPO_BASE};
_chdir($RB);

if ( @ARGV and $ARGV[0] eq 'POST_CREATE' ) {
    my $repo = $ARGV[1];
    create_alternates($repo);

    exit 0;
}

# not interested in any other triggers
exit 0;

sub create_alternates {
    my $pr      = shift;

    my $refrepos = git_config( $pr, "^gitolite-options\\.reference\\.repo.*/" );
    my @alts = map { split } values %$refrepos;
    for my $alt (@alts) {
        if ( repo_missing($alt) ) {
            _warn "Reference repo $alt is not a gitolite repo"
        }
        _print( "$RB/$pr.git/objects/info/alternates", "$RB/$alt.git/objects\n" );
    }
}
