#!/usr/bin/perl
use strict;
use warnings;

# you need 2 disposable userids: sam, frodo.  Then the test user (say
# "g3") needs to be able to sudo into them.  Put this in /etc/sudoers:

#       g3 ALL = (sam,frodo) NOPASSWD: ALL

$ENV{TSH_ERREXIT} = 1;

# this is hardcoded; change it if needed
use lib "src/lib";
use Gitolite::Test;
use Cwd;
my $workdir = getcwd();
my $h = $ENV{HOME};
my $t;   # temp vars

# basic tests
# ----------------------------------------------------------------------

try "plan 82";
##  try "DEF POK = !/DENIED/; !/failed to push/";

##  confreset;confadd '

##  ';

##  try "ADMIN_PUSH set1; !/FATAL/" or die text();

# ----------------------------------------------------------------------

my $bd = `gitolite query-rc -n GL_BINDIR`;

# switch keys
sub swk {
    my $k = shift;
    system("cp $bd/../t/keys/$k $h/.ssh/id_rsa");
    system("cp $bd/../t/keys/$k.pub $h/.ssh/id_rsa.pub");
}

sub all {
    try "F " . join(" ", @_);
    try "S " . join(" ", @_);
}

try "
    DEF F   =   sudo -u frodo -i
    DEF S   =   sudo -u sam -i
";

try "
    $bd/../t/mirror-test-setup-reference.sh;   ok or die mirror setup shell script failed
        /hello server-frodo, this is frodo/
        /hello server-sam, this is frodo/
        /hello server-frodo, this is sam/
        /hello server-sam, this is sam/
        /hello admin, this is frodo/
        /Initialized empty .*/gitolite-admin.git/
        /Initialized empty .*/testing.git/
        /Initialized empty .*/big-reference-repo.git/
        /Initialized empty .*/big-fork.git/
        /Initialized empty .*/empty-reference-repo.git/
        /Initialized empty .*/empty-fork.git/
        /Initialized empty .*/gitolite-admin.git/
        /Initialized empty .*/testing.git/
        /Initialized empty .*/big-reference-repo.git/
        /Initialized empty .*/big-fork.git/
        /Initialized empty .*/empty-reference-repo.git/
        /Initialized empty .*/empty-fork.git/
";

# push to frodo and see sam change
try "
    git clone frodo\@localhost:gitolite-admin fga
        ok; /Cloning into 'fga'.../
    cd fga;                             ok
    cp $bd/../t/keys/u*.pub keydir;     ok
    git add keydir;                     ok
    git commit -m 6keys;                ok
    git push;                           ok
        /To frodo\@localhost:gitolite-admin/
        /master -> master/
    sleep 5
    git rev-parse HEAD
";

chomp($t = text());

try "
    git ls-remote sam\@localhost:gitolite-admin
        ok; /$t/
";

try "
    cd ..

";

# Populate big-reference-repo on frodo with lots of commits
try "
    git clone frodo\@localhost:big-reference-repo
                                ok; /Cloning into 'big-reference-repo'.../
    cd big-reference-repo;        ok
";
for (1 .. 10) {
    try "empty";
}
try "
    git push origin master;     ok; /master -> master/
    sleep 5
    git rev-parse HEAD
";

chomp($t = text());

try "
    git ls-remote frodo\@localhost:big-reference-repo
        ok; /$t/
    git ls-remote sam\@localhost:big-reference-repo
        ok; /$t/
";

try "
    cd ..

";

try "
    git clone frodo\@localhost:big-fork
                                ok; /Cloning into 'big-fork'.../
    cd big-fork;                        ok
    git remote add reference frodo\@localhost:big-reference-repo
    git fetch reference
    git reset --hard reference/master
    empty
    git push origin master;         ok; /master -> master/
    sleep 5
    git rev-parse HEAD
";

chomp($t = text());

try "
    git ls-remote frodo\@localhost:big-fork
        ok; /$t/
    git ls-remote sam\@localhost:big-fork
        ok; /$t/
";

try "
    sudo -u frodo -i git --git-dir repositories/big-reference-repo.git count-objects
                                ok; /11 objects, 44 kilobytes/
    sudo -u frodo -i git --git-dir repositories/big-fork.git count-objects
                                ok; /1 objects, 4 kilobytes/
    sudo -u sam -i git --git-dir repositories/big-fork.git count-objects
                                ok; /1 objects, 4 kilobytes/
";

try "
    cd ..

";

try "
    git clone frodo\@localhost:empty-fork
                                ok; /Cloning into 'empty-fork'.../
    cd empty-fork
    empty
    git push origin master;     ok; /master -> master/
    sleep 5
    git rev-parse HEAD
";

chomp($t = text());

try "
    git ls-remote frodo\@localhost:empty-fork
        ok; /$t/
    git ls-remote sam\@localhost:empty-fork
        ok; /$t/
";

try "
    sudo -u frodo -i git --git-dir repositories/empty-reference-repo.git count-objects
                                ok; /0 objects, 0 kilobytes/
    sudo -u frodo -i git --git-dir repositories/empty-fork.git count-objects
                                ok; /2 objects, 8 kilobytes/
    sudo -u sam -i git --git-dir repositories/empty-fork.git count-objects
                                ok; /2 objects, 8 kilobytes/
";

try "
    git clone frodo\@localhost:empty-reference-repo
                                ok; /Cloning into 'empty-reference-repo'.../
    cd empty-reference-repo;        ok
    empty
    git push origin master;     ok; /master -> master/
    sleep 5
    git rev-parse HEAD
";

chomp($t = text());

try "
    git ls-remote frodo\@localhost:empty-reference-repo
        ok; /$t/
    git ls-remote sam\@localhost:empty-reference-repo
        ok; /$t/
";

try "
    sudo -u frodo -i git --git-dir repositories/empty-reference-repo.git count-objects
                                ok; /2 objects, 8 kilobytes/
    sudo -u frodo -i git --git-dir repositories/empty-fork.git count-objects
                                ok; /2 objects, 8 kilobytes/
    sudo -u sam -i git --git-dir repositories/empty-fork.git count-objects
                                ok; /2 objects, 8 kilobytes/
";
